config/routes.rb
Psychlopedia::Application.routes.draw do
  scope(path_names: {new: 'nueva'}) do
    resources :experiences, path: 'experiencias'
  end

  get 'search', to: 'experiences#search'
  get 'on/:category', to: 'experiences#on_category', as: 'category', path: 'en/:category'

  get 'about', to: 'infrastructure#about', path: 'que'
  get 'style', to: 'infrastructure#style', path: 'estilo'
  get 'legal', to: 'infrastructure#legal', path: 'legal'
  get 'privacy', to: 'infrastructure#privacy', path: 'privacidad'

  get 'admin', to: 'god#index', path: 'admin'

  resource :session, only: [:new, :create, :destroy]

  root to: 'experiences#index'
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :experience_categories
  has_many :experiences, through: :experience_categories
end

app/models/cocktail.rb
class Cocktail < ActiveRecord::Base
  belongs_to :experience
end

app/models/experience.rb
class Experience < ActiveRecord::Base
  extend FriendlyId

  has_many :experience_categories
  has_many :categories, through: :experience_categories, dependent: :destroy

  has_many :cocktails, dependent: :destroy
  accepts_nested_attributes_for :cocktails, reject_if: lambda { |cocktail| cocktail[:substance].blank? && cocktail[:dosage].blank? }

  friendly_id :title, use: :slugged
  is_impressionable

  validates :pseudonym, presence: true, length: { maximum: 25 }
  validates :title, presence: true
  validates :body, presence: true

  before_save :defaults

  default_scope { order('created_at DESC') }

  scope :approved, -> { where(is_approved: true) }

  # XXX: a poor's man (and a poor's mind) search engine.
  def self.search(query)
    @results = []
    ["%#{query}", "%#{query}%", "#{query}%"].each do |query|
      ["title", "pseudonym"].each do |field|
        candidates = Experience.approved.where("LOWER(#{field}) LIKE ?", query)
        candidates.each { |candidate| @results << candidate } unless candidates.empty?
      end
    end
    @results.uniq
  end

  def defaults
    self.publication_date = Date.today
  end

  # will_paginate per-page limit
  def self.per_page
    15
  end

  def approve
    self.is_approved = true
    save
  end

  def categories_used
    self.categories.map(&:name).map(&:downcase)
  end
end

app/models/experience_category.rb
class ExperienceCategory < ActiveRecord::Base
  belongs_to :experience
  belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :logged_in?

  private

  def logged_in?
    session[:admin]
  end
end

app/controllers/experiences_controller.rb
class ExperiencesController < ApplicationController
  before_action :set_experience, only: [:show, :update, :edit, :destroy]
  before_action :check_admin, only: [:edit, :destroy]
  before_action :has_permission_to_vote, only: [:update]
  before_action :set_title, only: [:index, :new, :show, :search]

  def index
    @experiences = Experience.approved.paginate(page: params[:page])
  end

  def show
    impressionist(@experience)
  end

  def update
    if logged_in? && @experience.update(experience_params)
      redirect_to @experience, notice: t('experiences.show.admin.update_successful')
    else
      render action: 'edit'
    end
  end

  def new
    @experience = Experience.new
    @experience.cocktails.build
  end

  def create
    @experience = Experience.new(experience_params)
    if gotcha_valid? && @experience.save
      redirect_to experiences_path, notice: t('experiences.waiting_for_approval')
    else
      render :new
    end
  end

  def search
    @query = extract_and_sanitize_query
    @results = Experience.search(@query)
  end

  def on_category
    @results = Category.find_or_create_by(name: params[:category]).experiences
    render :categories
  end

  def edit
    @experience.cocktails.build if @experience.cocktails.empty?
  end

  def destroy
    @experience.destroy
    redirect_to admin_path
  end

  private

  def set_experience
    @experience = Experience.friendly.approved.find(params[:id]) rescue Experience.none
  end

  def set_title
    if params[:query]
      translated_title_for_action = t("experiences.#{action_name}_title", query: extract_and_sanitize_query)
    elsif action_name == 'show'
      translated_title_for_action = t("experiences.#{action_name}_title", experience_title: @experience.title.split.map(&:capitalize).join(' '))
    else
      translated_title_for_action = t("experiences.#{action_name}_title")
    end
    @page_title = "Psychlopedia - #{translated_title_for_action}"
  end

  def extract_and_sanitize_query
    params[:query].downcase.parameterize
  end

  def experience_params
    permitted = params.require(:experience).permit(:title, :pseudonym, :body, :set, :setting, :locale,
                                                   cocktails_attributes: [:id, :substance, :dosage])
    permitted.delete_if { |key, value| value.blank? }
  end

  def check_admin
    redirect_to experiences_path unless logged_in?
  end
end

app/controllers/god_controller.rb
class GodController < ApplicationController
  before_action :is_admin?

  def index
    @experiences = Experience.all
  end

  private

  def is_admin?
    redirect_to new_session_path unless session[:admin]
  end
end

app/controllers/infrastructure_controller.rb
class InfrastructureController < ApplicationController
  before_action :set_title

  def about; end
  def style; end
  def legal; end
  def privacy; end

  private

  def set_title
    translated_title = t("psychlopedia.titles.#{action_name}_title")
    @page_title = "Psychlopedia - #{translated_title}"
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    if params[:password] == ADMIN_PASSWORD
      session[:admin] = true
    end

    redirect_to admin_path
  end

  def destroy
    session.destroy
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def page_title
    @page_title || 'Psychlopedia'
  end

  def relocalize_url(locale)
    naked_url, params = request.original_url.split('?')
    if params
      relocalized_params = params.split('&').delete_if { |param| param =~ /locale/ }
      relocalized_params << "locale=#{locale}"
      "#{naked_url}?#{relocalized_params.join('&')}"
    else
      "#{naked_url}?locale=#{locale}"
    end
  end

  def active_category?(category)
    request.original_url =~ /#{category.slug}/
  end
end

app/helpers/experiences_helper.rb
module ExperiencesHelper
  def markdown(text)
    markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML, hard_wrap: true, filter_html: true, autolink: true, no_intraemphasis: true)
    markdown.render(text).html_safe
  end

  def titleize(title)
    title.split.map(&:capitalize).join(' ')
  end

  def truncate_and_titleize(title, length = 40, omission = '...')
    truncate(titleize(title), length: length, omission: omission)
  end

  def disqus_thread_url(experience)
    experience_path(experience) + '#disqus_thread'
  end
end

app/views/experiences/_experiences.html.erb
<div>
  <% @experiences.each do |experience| -%>
    <li class="experience">
      <%= l(experience.created_at.to_date, format: :short).upcase -%>
      <%= link_to truncate_and_titleize(experience.title), experience_path(experience), title: titleize(experience.title) -%>
      <%= t('psychlopedia.misc.by') -%>
      <%= experience.pseudonym -%>
      <%= link_to t('experiences.comments_placeholder'), disqus_thread_url(experience), style: 'font-size: .8em;' -%>
    </li>
  <%- end -%>
  <%= will_paginate @experiences, page_links: false -%>
</div>

app/views/experiences/_form.html.erb
<%= form_for(@experience) do |f| -%>
  <%- if @experience.errors.any? -%>
    <div id="error_explanation">
      <h2><%= pluralize(@experience.errors.count, "error") -%> prohibited this experience from being saved:</h2>

      <ul>
      <%- @experience.errors.full_messages.each do |message| -%>
        <li><%= message -%></li>
      <%- end -%>
      </ul>
    </div>
  <%- end -%>

  <div class="field">
    <%= f.label t('experiences.addition.title') -%><br>
    <%= f.text_field :title, required: true -%>
  </div>

  <div class="field">
    <%= f.label t('experiences.addition.pseudonym') -%><br>
    <%= f.text_field :pseudonym, required: true -%>
  </div>

  <div>
    <span class="enrichment"><%= t('experiences.addition.more_information.legend') -%></span>
  </div>

  <div class="extra">
    <div class="field">
      <%= f.fields_for :cocktails do |builder| -%>
        <%= builder.label :substance, t('experiences.addition.more_information.substance') -%>
        <%= builder.text_field :substance, placeholder: t('experiences.addition.more_information.substance_placeholder') -%>
        <%= builder.label :dosage, t('experiences.addition.more_information.dosage') -%>
        <%= builder.text_field :dosage, placeholder: t('experiences.addition.more_information.dosage_placeholder') -%>
      <%- end -%>
    </div>

    <div class="set-and-setting">
      <p><%= t('experiences.addition.set_setting_short_description') -%></p>
      <p><%= t('experiences.addition.set_setting_long_description_html') -%></p>
    </div>

    <div class="field">
      <%= f.label t('experiences.addition.more_information.set') -%>
      <%= f.text_field :set -%>
    </div>

    <div class="field">
      <%= f.label t('experiences.addition.more_information.setting') -%>
      <%= f.text_field :setting -%>
    </div>
  </div>

  <div id="experience" class="field">
    <%= f.label t('experiences.addition.body') -%><br>
    <%= f.text_area :body, cols: 40, rows: 20, required: true -%>
  </div>

  <%- if action_name == 'new' -%>
    <div class="field">
      <%= gotcha_error -%>
      <%= gotcha -%>
    </div>
  <%- end -%>

  <div class="field">
    <%= t('experiences.addition.markdown_formatting_html', link: link_to('Markdown', 'https://daringfireball.net/projects/markdown/', target: '_blank')) -%>
    <br><br>
  </div>

  <div class="actions">
    <%= f.hidden_field :locale, value: I18n.locale -%>
    <%= f.submit t('experiences.addition.submit') -%>
  </div>
<%- end -%>

app/views/experiences/_search_results.html.erb
<%- unless @results.empty? -%>
  <p class="results-title"><%= t('experiences.search_form.results_html', query: @query) -%></p>
  <% @results.each do |experience| -%>
    <li class="experience search-result">
      <%= l(experience.created_at.to_date) -%>
      <%= link_to (truncate(titleize(experience.title), length: 45, omission: '...')), experience_path(experience), title: titleize(experience.title) -%>
      <%= t('psychlopedia.misc.by') -%>
      <%= experience.pseudonym -%>
      <div class="snippet">
        <%= truncate(experience.body, length: 250, omission: '...') -%>
        <%= link_to t('experiences.random.keep_reading'), experience_path(experience) -%>
      </div>
    </li>
  <%- end -%>
<%- else -%>
  <div class="no-results">
    <p><%= t('experiences.search_form.no_results_html', query: @query) -%></p>
    <p><%= link_to t('experiences.search_form.contribute_instead'), new_experience_path, class: 'create' -%></p>
  </div>
<%- end -%>

app/views/experiences/about.html.erb
<div class="about">
  <p>
    Bienvenidos a <span class="self emphasis">Psychlopedia</span>.
  </p>
  <p>
    Psychlopedia es un archivo de <span class="emphasis">experiencias</span> bajo <%= link_to 'estados alterados de la conciencia', 'https://es.wikipedia.org/wiki/Estado_alterado_de_conciencia', target: '_blank' -%> en español. Nuestra intención es convertirnos en una herramienta confiable de educación y farmacovigilancia que asista al <%= link_to 'ejercicio seguro', 'https://es.wikipedia.org/wiki/Reducci%C3%B3n_del_da%C3%B1o', target: '_blank' -%> de la psiconáutica.
  </p>
  <p>
    Podés <%= link_to 'buscar', experiences_path -%>, <%= link_to 'leer', experiences_path -%>, comentar y <%= link_to 'crear', new_experience_path -%> experiencias en este depósito; tanto si querés compartir una vivencia como si estás buscando información sobre su carácter general, Psychlopedia está para servir esos propósitos.
  </p>
  <p>
    En contraste con los clásicos e imponentes <%= link_to 'Erowid Experience Vaults', 'https://www.erowid.org/experiences/', target: '_blank' -%>, Psychlopedia usa un sistema abierto de moderación y valuación de experiencias. Somos una vibrante comunidad virtual de individuos, aún en expansión, y pondremos nuestro mejor esfuerzo en explotar el poder de la comunicación. Podés <%= link_to 'leer más al respecto por acá', style_guide_path -%>.
  </p>
  <p>
    Este proyecto está construído <span class="emphasis">por psiconautas para psiconautas</span>.
    Nos encanta conversar, y cualquier tipo de feedback es felizmente recibido; por favor,
      <%= mail_to 'airOnGString@gmail.com', 'no dudes en escribirnos', subject: "kestapasando" -%>.
  </p>
</div>

app/views/experiences/categories.html.erb
<% @results.each do |experience| -%>
  <li class="experience">
    <%= l(experience.created_at.to_date) -%>
    <%= link_to (truncate(titleize(experience.title), length: 45, omission: '...')), experience_path(experience), title: titleize(experience.title) -%>
    <%= t('psychlopedia.misc.by') -%>
    <%= experience.pseudonym -%>
  </li>
<%- end -%>

app/views/experiences/disclaimer.html.erb
<div class="disclaimer">
  <p>
    Estas páginas discuten temas definitivamente controversiales. El consumo de ciertos psicoactivos con fines recreacionales 
    está criminalizado actualmente en la mayoría de los países del mundo, y Argentina no es la excepción. Desde que miembros 
    de la comunidad científica, médica, y periodística comenzaron a sugerir la legalización como una estrategia para reducir 
    el daño asociado al narcotráfico, allá por los pálidos y ojerosos 90's, padecemos de la creciente agresividad de los 
    sistemas que controlan y regulan nuestro comportamiento y sus proponentes. Cualquier persona discutiendo el uso de 
    psicotrópicos está caminando al borde del abismo; una vez que comenzamos a contar de qué manera se hace, el asunto se 
    pone aún más peligroso.
  </p>
  <p>
    Hacemos Psychlopedia porque consideramos importante la disponibilización de información de alta calidad a todas las personas. 
    Tomaremos los recaudos necesarios para protegernos, priorizando la viabilidad de este emprendimiento. Sin más 
    preámbulo, a continuación sigue un aviso legal que bien podría ser inútil ante una corte de justicia:
  </p>
  <p class="bald">
    No es la intención ni la finalidad de Psychlopedia influenciar a cualquier persona a cometer un delito. Psychlopedia explícitamente 
    instruye a todos sus lectores a no violar ninguna ley, sea internacional, nacional, provincial, regional, municipal u otras 
    categorías o leyes aplicables sobre la información presentada en cualquiera de los relatos publicados aquí digitalmente o 
    mediante otros métodos de publicación, sean informáticos o no. Específicamente, se recomienda enfáticamente a los lectores no ingerir, injectar, fumar, aspirar o 
    proceder con cualquier otro método de administración sobre ninguna droga, legal o ilegal (excepto drogas legales recetadas por un profesional), 
    ni participar en la manufactura, distribución, síntesis, análisis u otros procedimientos sobre ninguna droga, legal o ilegal. 
  </p>
  <p class="bald">
    Toda la información de este sitio es presentada SÓLO CON FINES EDUCACIONALES.
  </p>
  <p class="bald">
    No hay garantía de que la información presente en este sitio sea precisa o válida de ninguna forma. Cualquier persona que 
    intente emprender cualquier procedimiento o acción basándose en estos contenidos es responsable total de cualquier resultado 
    con el que se encuentre. Psychlopedia, el proveedor de este sitio, y sus miembros no serán responsables en ninguna instancia.
  </p>
</div>

app/views/experiences/edit.html.erb
<h1 style="margin-bottom:20px;">Modo de edición</h1>

<%= render 'form' %>

<%= link_to 'Show', @experience %> |
<%= link_to 'Back', admin_path %>

app/views/experiences/index.html.erb
<%- unless @experiences.empty? -%>
  <%- if flash[:notice] -%>
    <p class="notice"><%= flash[:notice] -%></p>
  <%- end -%>
  <div class="search">
    <%= form_tag(search_path, method: :get) do -%>
      <%= text_field_tag(:query) -%>
      <%= submit_tag t('experiences.search') -%>
    <%- end -%>
  </div>
  <% @experiences.each do |experience| -%>
    <li class="experience">
      <%= l(experience.created_at.to_date, format: :short).upcase -%>
      <%= link_to truncate_and_titleize(experience.title), experience_path(experience), title: titleize(experience.title) -%>
      <%= t('psychlopedia.misc.by') -%>
      <%= experience.pseudonym -%>
      <%= link_to t('experiences.comments_placeholder'), disqus_thread_url(experience), style: 'font-size: .8em;' -%>
    </li>
  <%- end -%>
  <%= will_paginate @experiences, page_links: false -%>
<%- else -%>
  <div class="no-data">
    <p><%= t('experiences.no_data') -%></p>
    <p><%= link_to t('experiences.no_data_invitation'), new_experience_path, class: 'create' -%></p>
  </div>
<%- end -%>

app/views/experiences/new.html.erb
<p class="new-disclaimer">
  <%= t('experiences.addition.disclaimer') -%>
</p>
<%= render 'form' %>

app/views/experiences/search.html.erb
<div class="search">
  <%= form_tag(search_path, method: :get) do -%>
    <%= text_field_tag(:query) -%>
    <%= hidden_field_tag(:locale, I18n.locale) -%>
    <%= submit_tag t('experiences.search') -%>
  <%- end -%>
</div>

<%= render 'search_results' %>

app/views/experiences/show.html.erb
<%- if @experience.present? -%>
  <div>
    <%- if flash[:notice] -%>
      <p class="notice"><%= flash[:notice] -%></p>
    <%- end -%>
    <%- if session[:admin] -%>
      <p style="margin-bottom:5px;"><%= link_to '~Editar', edit_experience_path(@experience) -%></p>
    <%- end -%>
    <div class="thingo">
      <h1 class="title" title="<%= titleize(@experience.title) -%>">
        <span class="self"><%= truncate_and_titleize(@experience.title) -%></span>
      </h1>
    </div>
    <h3 class="whoandwhen">
      <%= t('psychlopedia.misc.by') -%>
      <%= @experience.pseudonym -%> &#8669;
      <%= l @experience.created_at.to_date, format: :long -%>
    </h3>
    <h4>
      <div class="categories">
        <%- unless @experience.categories.empty? -%>
        <p>Categorías: </p>
          <%- @experience.categories_used.each do |category| -%>
          <span class="category"><%= link_to category, category_path(category) -%></span>
          <%- end -%>
        <%- end -%>
      </div>
    </h4>
    <div style="margin-bottom:20px;">
      <%- if @experience.cocktails.present? -%>
        <%- @cocktail = @experience.cocktails.first -%>
        <p style="font-size:1em;"><span class="emphasis"><%= t('experiences.show.substance') -%>:</span> <%= @cocktail.substance -%></p>
        <p style="font-size:1em;"><span class="emphasis"><%= t('experiences.show.dosage') -%>:</span> <%= @cocktail.dosage -%></p>
      <%- end -%>
      <%- if @experience.set.present? -%>
        <p style="font-size:1em;"><span class="emphasis"><%= t('experiences.show.set')%>:</span> <%= @experience.set -%></p>
      <%- end -%>
      <%- if @experience.setting.present? -%>
        <p style="font-size:1em;"><span class="emphasis"><%= t('experiences.show.setting') -%>:</span> <%= @experience.setting -%></p>
      <%- end -%>
    </div>
    <div class="etxt">
      <%= markdown(@experience.body) -%>
    </div>
    <%- if @experience.source.present? && @experience.source != 'psychlopedia' -%>
      <div class="source">
        <p><%= t('experiences.show.source') -%>: <%= @experience.source -%></p>
      </div>
    <%- end -%>
    <hr>
    <div id="comments">
      <div id="disqus_thread"></div>
      <script type="text/javascript">
          var disqus_shortname = 'psychlopedia';
          (function() {
              var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
              dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
              (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
          })();
      </script>
      <noscript><%= t('experiences.show.no_script') -%></noscript>
      <a href="http://disqus.com" class="dsq-brlink"><%= t('experiences.show.disqus_placeholder') -%> <span class="logo-disqus">Disqus</span></a>.
    </div>
  </div>
<%- end -%>

app/views/god/index.html.erb
<h1>Experiencias</h1>

<table style="margin-top:20px;">
  <tbody>
    <% @experiences.each do |experience| -%>
      <tr>
        <td><span class="emphasis"><%= experience.title -%></span></td>
        <td><%= link_to 'Ver', experience -%></td>
        <td><%= link_to 'Editar', edit_experience_path(experience) -%></td>
        <td><%= link_to 'Eliminar', experience, method: :delete, data: { confirm: '¿Estás seguro?' }, style: "color:red;" -%></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nueva Experiencia', new_experience_path -%> | <%= link_to 'Salir', session_path, method: :delete, data: { confirm: '¿Salir?' } -%>

app/views/infrastructure/about.en.html.erb
<div class="about">
  <p>
    <span class="self emphasis">Psychlopedia</span> is an
    <%= link_to 'altered states of consciousness', 'http://en.wikipedia.org/wiki/Altered_state_of_consciousness', target: '_blank' -%>
    experience archive.
  </p>
  <p>
    You can <%= link_to 'create', new_experience_path -%>, <%= link_to 'read', experiences_path -%> and
    <%= link_to 'search', experiences_path -%> experiences in this repository; if you want to share your experience or search our collection
    and read about the subjective aspects of a particular substance- or technology-induced experience, Psychlopedia aims to help both purposes.
  </p>
  <p>
    Unlike the well-known, <span style="font-style:italic;">par excellence</span> psychoactive-induced experiences resource
    <%= link_to 'Erowid Experience Vaults', 'https://www.erowid.org/experiences/', target: '_blank' -%>,
    Psychlopedia embraces community-driven self-moderation based on simple guidelines and an open rating system.
    You can <%= link_to 'read more about it here', style_path -%>.
  </p>
  <p>
    This strategic tool of pharmacovigillance and post-black market surveillance is built by psychonauts for everyone
    wanting to explore the qualitative facets of self-experimentation, an actual and growing real-world practice.
  </p>
  <p>
    We love to talk, and we are happy to receive any kind of constructive feedback;
    please, <%= mail_to 'airOnGString@gmail.com', "don't hesitate to contact us", subject: "Hello, Psychlopedia!" -%>.
  </p>
</div>

app/views/infrastructure/about.html.erb
<div class="about">
  <p>
    <span class="self emphasis">Psychlopedia</span> es un archivo digital de experiencias bajo
    <%= link_to 'estados alterados de la conciencia', 'https://es.wikipedia.org/wiki/Estado_alterado_de_conciencia', target: '_blank' -%>
    en español.
  </p>
  <p>
    Podés <%= link_to 'crear', new_experience_path -%>, <%= link_to 'leer', experiences_path -%> y <%= link_to 'buscar', experiences_path -%>
    experiencias en este repositorio; tanto si querés compartir un relato como buscar en nuestra compilación y leer sobre el carácter subjetivo
    de una experiencia inducida por sustancias o tecnologías psicoactivas, apuntamos a contribuir en ambos casos.
  </p>
  <p>
    Podés leer más sobre Psychlopedia y la creación y valoración de experiencias en nuestra <%= link_to 'guía de estilo', style_path -%>.
  </p>
  <p>
    Esta herramienta estratégica de farmacovigilancia y control post-mercado negro está (siendo) construída por psiconautas
    para todas las personas interesadas en la exploración de los aspectos cualitativos de la auto-experimentación.
    Nos alegra recibir cualquier forma y cantidad de feedback constructivo; por favor,
    <%= mail_to 'airOnGString@gmail.com', "no dudes de ponerte en contacto con nosotros", subject: "Hola, Psychlopedia!" -%>.
  </p>
  <p>
    <a href="https://twitter.com/Psiclopedia" class="twitter-follow-button" data-size="large" data-show-count="true" data-lang="es">Seguí a @Psiclopedia</a>
  </p>
</div>

app/views/infrastructure/legal.en.html.erb
We are currently translating this section. Sorry for the inconvenience.

app/views/infrastructure/style.en.html.erb
Holy smokes, Batwoman.

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= page_title -%></title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="description" content="Psychlopedia es un archivo digital de experiencias bajo estados alterados de la conciencia.">
    <meta name="keywords" content="reduccion daños psicodelia psicodelicos experiencias farmacovigilancia">
    <meta name="author" content="5vankmajer">
    <meta name="viewport" content="device-width, initial-scale=1, user-scalable=no">
    <meta property="og:type" content="website">
    <meta property="og:url" content="https://psychlopedia.herokuapp.com">
    <meta property="og:title" content="Psychlopedia - El ágora del psiconauta.">
    <meta property="og:site_name" content="Psychlopedia">
    <meta property="og:description" content="Psychlopedia es el archivo de experiencias psicodélicas en español.">
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= favicon_link_tag %>
  </head>
  <body>
    <div id="container" class="cf">
      <header id="header">
        <nav>
          <ul>
            <li><%= link_to t('menu.experiences'), experiences_path, accesskey: 'e' -%></li>
            <li><%= link_to t('menu.add'), new_experience_path, accesskey: 'c' -%></li>
            <li><%= link_to t('menu.what_is_this'), about_path, class: 'what' %></li>
            <li class="footnotes"><%= link_to t('menu.legal'), legal_path -%> · <%= link_to t('menu.privacy'), privacy_path -%></li>
          </ul>
        </nav>
      </header>
      <div id="main" role="main">
        <%= yield %>
      </div>
    </div>
    <script type="text/javascript">
      UserVoice=window.UserVoice||[];(function(){var uv=document.createElement('script');uv.type='text/javascript';uv.async=true;uv.src='//widget.uservoice.com/b362QGwgVSMnyEbSJprTw.js';var s=document.getElementsByTagName('script')[0];s.parentNode.insertBefore(uv,s)})();

      UserVoice.push(['set', {
        accent_color: '#448dd6',
        trigger_color: 'white',
        trigger_background_color: '#6aba2e'
      }]);

      UserVoice.push(['addTrigger', { mode: 'contact', trigger_position: 'bottom-right' }]);
      UserVoice.push(['autoprompt', {}]);
    </script>
    <script type="text/javascript">
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-50157609-1', 'psychlopedia.herokuapp.com');
      ga('send', 'pageview');
    </script>
    <script type="text/javascript">
      var disqus_shortname = 'psychlopedia';
      (function () {
        var s = document.createElement('script'); s.async = true;
        s.type = 'text/javascript';
        s.src = 'https://' + disqus_shortname + '.disqus.com/count.js';
        (document.getElementsByTagName('HEAD')[0] || document.getElementsByTagName('BODY')[0]).appendChild(s);
      }());
    </script>
    <script type="text/javascript">
      !function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");
    </script>
  </body>
</html>